### ISSUE TITLE
LNK2019 (VirtualAllocFromApp)

### ISSUE THREAD

**Issue by Guekka** [foonathan/memory#101]
Looking at older PRs, it was introduced by #80. I don't know why, but replacing in virtual_memory.cpp :
`#if (_MSC_VER <= 1900)` 
with 
`#if (_MSC_VER <= 1900) || WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)` 
fixes it. Not sure if it is a real fix.

**Comment by foonathan** [comment]
The fix does make sense. The PR originally checked only for the partition, but that didn't work for older MSVCs, so it was replaced by the version check. Doing both would have been the proper solution.

Can you do a PR?
