### ISSUE TITLE
config_impl.hpp installed in wrong place?

### ISSUE THREAD

**Issue by jwdevel** [foonathan/memory#104]
I'm just getting started with this library, so maybe I have some simple problem.

I created a build with these steps (note: not exactly matching the docs, but I think the issue remains, regardless):

```
$ mkdir -p build/debug
$ pushd build/debug
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=install -DCMAKE_BUILD_TYPE="Debug" -DFOONATHAN_MEMORY_BUILD_EXAMPLES=OFF -DFOONATHAN_MEMORY_BUILD_TESTS=OFF ../..
$ make install
$ popd
```

This results in the following file structure:

```
build/debug/install/include/foonathan_memory/config_impl.hpp        <- one file at top level
build/debug/install/include/foonathan_memory/foonathan/memory/...   <- all the normal includes
```

This seems wrong to me, given that in the `config.hpp` file, it has: `#include "config_impl.hpp"`. Surely those files are meant to sit next to each other?
Certainly, having a generic-named file like `config_impl.hpp` at the top-level is asking for naming collisions.

Easy to fix manually, but figured I'd mention this in case I misunderstand something.

**Comment by foonathan** [comment]
No, that seems like a bug. Good catch, thanks, I'll fix it.
