### ISSUE TITLE
[foonathan::memory] Allocator foonathan::memory::memory_pool (at 0x3a8fc1c8) received invalid size/alignment 56, max supported is 48 terminate called after throwing an instance of 'foonathan::memory::bad_node_size'

### ISSUE THREAD

**Issue by Baren123** [foonathan/memory#124]
When I run my cross-compiled fastrtps application on the aarch64 linux platform, I see following exception：

[foonathan::memory] Allocator foonathan::memory::memory_pool (at 0x559f6319a8) received invalid size/alignment 56, max supported is 48terminate called after throwing an instance of 'foonathan::memory::bad_node_size' what(): allocation node size exceeds supported maximum of allocator

how can I solve it?

**Comment by foonathan** [comment]
Duplicate of: #123
