### ISSUE TITLE
trouble with unordered_map and stateful allocators

### ISSUE THREAD

**Issue by meuter** [foonathan/memory#13]
Hi,

I'm having trouble compiling an unordered_map with a custom stateful raw allocator. I'm on OSX 12.10.6 with clang:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Here's a small sample program to demonstrate the problem:
```c++
#include <cstdio>
#include <cstdlib>
#include <foonathan/memory/container.hpp>

namespace my
{
    struct raw_stat_mallocator
    {
        using is_stateful = std::integral_constant<bool, true>; 

        size_t total;
        size_t current;

        void* allocate_node(std::size_t size, std::size_t alignment)
        {
            printf("[ %p ] Allocating %zd bytes (%zd total, %zd current)\n", this, size, total, current);
            total += size;
            current += size;
            return malloc(size);
        }

        void deallocate_node(void *node, std::size_t size, std::size_t alignment) noexcept
        {
            printf("[ %p ] Deallocating %zd bytes (%zd total, %zd current)\n", this, size, total, current); 
            current -= size;
            free(node);
        }
    };  

    using string = foonathan::memory::string<my::raw_stat_mallocator>;

    template<typename K, typename V>
    using hash_map = foonathan::memory::unordered_map<K, V, my::raw_stat_mallocator>;
}


int main()
{
    auto ral = my::raw_stat_mallocator();
    auto m1 = my::hash_map<int, my::string>(ral);
    auto m2 = my::hash_map<my::string, int>(ral);

    m1[2] = my::string("hello", ral);  // does not compile
    (void)m1[2]; // does not compile either
    m2[my::string("world", ral)] = 5; // this works however
    return EXIT_SUCCESS;
}
```

It looks like std::unordered_map does not propagate the allocator to the construction of the V when constructing std::pair<K,V>. It seems to work for the K though which is weird. Am I doing something wrong? Can I somehow provide the allocator explicitly when accessing the map? Maybe it's a problem with clang's particular implementation of the std::unordered_map? Do you have any idea of how to fix/work around this?

Thanks!

-Cédric

**Comment by foonathan** [comment]
I need to look into that.

For me it also seems that there is no hashing for strings with custom allocators.

**Comment by foonathan** [comment]
Okay, I think I found the issue.

The `operator[]` of map first needs to create a default constructed key-value pair. However, `my::string` uses a stateful allocator and stateful allocators aren't default constructible, so it fails. You just can't use `operator[]`, just like you can't use it if you have a "normal" non-default constructible type.

However, the error message could be nicer.

**Comment by meuter** [comment]
First of all, thanks for looking into this! Following posting the issue yesterday, I started looking into allocators in a bit more depth. I found this talk from CPPCon2014 on the subject:

[Making Allocators Work - Part 1](https://www.youtube.com/watch?v=YkiYOP3d64E)
[Making Allocators Work - Part 2](https://www.youtube.com/watch?v=Q5kyiFevMJQ)

And there is a [bit](https://www.youtube.com/watch?v=Q5kyiFevMJQ#t=49m34s) about building container of non trivial objects and how one should go about and do it. He mentions `std::scoped_allocator_adaptor<...>` which are precisely there to inject the allocator of the container in the  constructor of the contained item by highjacking the `construct` method of the allocator. His example is a `vector<string>` allocated using a shared memory allocator which is should both be used to allocate the `vector` memory as well as the `string` memory. 

So this morning, I thought I'd just use that and it should work. So I rewrote the type system as follows:

```c++
    template<typename T>
    using allocator = std::scoped_allocator_adaptor<foonathan::memory::std_allocator<T, my::raw_stat_mallocator>>;

    template<typename C>
    using basic_string = std::basic_string<C, std::char_traits<C>, allocator<C>>;

    using string = std::basic_string<char>;

    template<typename K, typename V>
    using hash_map = std::unordered_map<K, V, std::hash<K>, std::equal_to<K>, allocator<std::pair<const K, V>>>;
```
But that does not compile either (something about `alloc_reference`not being able to access a private base class or something). However, trying some more random stuff, I simply removed the `scoped_allocator_adaptor` from the above type system. And hey, it works. I'm still puzzled, because it looks like I'm just redefining what's done in `Container.hpp`, but obviously there is subtle difference that eludes me at the moment. I'll continue digging.

Anywho, here's what I've got so far:

```c++
    // ... same as above

    template<typename T>
    using allocator = foonathan::memory::std_allocator<T, my::raw_stat_mallocator>;

    template<typename C>
    using basic_string = std::basic_string<C, std::char_traits<C>, allocator<C>>;

    using string = std::basic_string<char>;

    template<typename K, typename V>
    using hash_map = std::unordered_map<K, V, std::hash<K>, std::equal_to<K>, allocator<std::pair<const K, V>>>;
}


int main()
{
    auto ral = my::raw_stat_mallocator();
    auto m1 = my::hash_map<int, my::string>(ral);
    auto m2 = my::hash_map<my::string, int>(ral);

    // both of these work fine and (added bonus) I don't have 
    // to explicitly instantiate the strings with ral :-)
    m1[2] = "hello"; 
    m2["hello"] = 2;
    return EXIT_SUCCESS;
}
```
which produced the following output, which seems reasonable to me:

```
[ 0x7fff5c438430 ] Allocating 48 bytes (0 total, 0 current)
[ 0x7fff5c438430 ] Allocating 16 bytes (48 total, 48 current)
[ 0x7fff5c438430 ] Allocating 48 bytes (64 total, 64 current)
[ 0x7fff5c438430 ] Allocating 16 bytes (112 total, 112 current)
[ 0x7fff5c438430 ] Deallocating 48 bytes (128 total, 128 current)
[ 0x7fff5c438430 ] Deallocating 16 bytes (128 total, 80 current)
[ 0x7fff5c438430 ] Deallocating 48 bytes (128 total, 64 current)
[ 0x7fff5c438430 ] Deallocating 16 bytes (128 total, 16 current)
```
