### ISSUE TITLE
Why beating around a bush?

### ISSUE THREAD

**Issue by DBJDBJ** [foonathan/memory#130]
There is no way to replace[ the flawed modern C++ allocator concept](https://thephd.dev/freestanding-noexcept-allocators-vector-memory-hole). 

But still, here you are with a new repo doing something like that? Exactly like that? Nothing like that?

Am I the only one who is confused here?

Kind regards

**Comment by foonathan** [comment]
The library does two things:

1. Provide a collection of allocators that use a different allocator concept.
2. Provide adaptors to use those allocators with the existing allocator concept.

Sure, we can't change the `Allocator` concept which means point 2 inherits all that disadvantages. But point 1 is still useful on its own and you can write containers against my allocator concept, completely ignoring the existence of standard allocators.
