### ISSUE TITLE
Building tests on Windows fails with `BUILD_SHARED_LIBS=ON`

### ISSUE THREAD

**Issue by MiguelCompany** [foonathan/memory#131]
Build fails with an unresolved external error:

```
default_allocator.obj : error LNK2001: unresolved external symbol "unsigned __int64 const foonathan::memory::virtual_memory_page_size" (?virtual_memory_page_size@memory@foonathan@@3_KB)
```

I've seen you are setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` [here](https://github.com/foonathan/memory/blob/main/CMakeLists.txt#L41), but note the following sentence, extracted from the CMake [docs](https://cmake.org/cmake/help/v3.23/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html):

```
For global data symbols, __declspec(dllimport) must still be used when compiling against the code in the .dll.
```
It seems we need a `__declspec(dllimport)` [here](https://github.com/foonathan/memory/blob/main/include/foonathan/memory/virtual_memory.hpp#L41)

**Comment by foonathan** [comment]
I'm not using windows and have never used DLL's, so I'd appreciate a PR.

**Comment by MiguelCompany** [comment]
An easy but API-breaking solution would be to convert that `extern const` into a method. That way, it will be automatically exported and imported.

Building the tests on the CI with `BUILD_SHARED_LIBS` on and off would be enough to check everything works ok.
