### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by MiguelCompany** [foonathan/memory#152]
Since the last release, there have been some [changes](https://github.com/foonathan/memory/compare/v0.7-2...main). 
I am particularly interested in #139 and #147.

@foonathan Do you think it's time for a new release?

**Comment by foonathan** [comment]
I agree, especially with the bugs reported in the last couple of weeks. I've tagged a new release: https://github.com/foonathan/memory/releases/tag/v0.7-3
