### ISSUE TITLE
Binary segregator deallocate always calls fallback_allocator

### ISSUE THREAD

**Issue by twiggler** [foonathan/memory#16]
The binary segregator always invokes the fallback_allocator when deallocating [arrays](https://github.com/foonathan/memory/blob/e3d82496afcd925bc335e6c4301f8baf72c4496e/include/foonathan/memory/segregator.hpp#L182 ) and [nodes](https://github.com/foonathan/memory/blob/e3d82496afcd925bc335e6c4301f8baf72c4496e/include/foonathan/memory/segregator.hpp#L164).

**Comment by foonathan** [comment]
Okay, I've fixed it on develop (an incomplete test case didn't catch it), will prepare a new release shortly.

**Comment by twiggler** [comment]
Thank you Jonathan for responding and fixing the issue in a timely manner.
Generally speaking, I really like the design of the library; clearly, a lot of thought has gone into it. 
Grüße aus Holland.
