### ISSUE TITLE
MinGW build fails due to "#warning"

### ISSUE THREAD

**Issue by burnpanck** [foonathan/memory#167]
`temporary_allocator.cpp` contains a check for `__MINGW64__` to decide whether or not to use `temporary_stack_initializer`.
If it does decide to use it, it emits a `#warning`. However, the file is compiled with `-Werror -Wall`, making this warning effectively an error. Furthermore, `-Wno-error=cpp` will probably not work, because GCC emits *another* warning ("#warning is a GCC extension", which is enabled by `-pedantic` and cannot be silenced independently).

To make this work, one would probably have to either remove the `#warning` or disable `-Werror` for that source file.
However, glancing over the comments on the issues that seem to be requiring this `temporary_stack_initializer` in the first place, it appears that this bug may have been fixed a few years ago:
- Original issue: https://sourceforge.net/p/mingw-w64/bugs/527/
- Linked issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83562

Thus, potentially, the check could be removed completely.

**Comment by foonathan** [comment]
Thanks, I've removed the checks.
