### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [foonathan/memory#19]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

Also would be perfect, if you will create conan recipes for other your libraries.

If you have any questions, just ask :-)

**Comment by foonathan** [comment]
I'm not going to maintain packaging for a package manager I'm not using.
If you provide a PR, I'll merge it.
