### ISSUE TITLE
which pool to use for dynamic sizes

### ISSUE THREAD

**Issue by gabyx** [foonathan/memory#21]
Is it possible to have a memory collection (log2 buckets) which has no maxnode size?
I have to following scenario, I receive binary message and I would like to have memory pool which provides me a `char` buffer for this binary messages. However I have no idea about the maximum size of the message. It can be that they are always below lets say 16kb and suddenly a message needs a buffer of 4mb. Can that be done with your pool collection?
Probably I misunderstand something here:

From the tests I see:

```cpp
memory_pool_collection<node_pool, identity_buckets, allocator_reference<test_allocator>>;
    test_allocator alloc;
    {
        const auto max_size = 16u;
        pools      pool(max_size, 1000, alloc);
```
meaning we have a block size of  1000bytes  and the maximum node  size (my buffer size) is fixed to 16bytes... So when I request 17bytes what happens?

Thanks a lot =)

**Comment by foonathan** [comment]
If you call `pool.allocate_node(17)`, it will throw a `bad_allocation_size` exception. This is the function called if you use the `std_allocator` with the pool (e.g. if you use a `memory::list` using that pool).

If you call `pool.try_allocate_node(17)`, it will return `nullptr`. Then you can try a different allocator. The class `fallback_allocator` automates that for you. You can say that it uses the pool by default, but e.g. `heap_allocator` as a fallback.

Note that `pool.try_allocate_node(16)` will also return `nullptr` if the pool is exhausted.

**Comment by foonathan** [comment]
There's `memory::allocate_shared` that you can use directly.

**Comment by gabyx** [comment]
When I try to use:
```
memory::memory_pool_collection<memory::node_pool, 
            memory::log2_buckets, 
            memory::fallback_allocator< memory::default_allocator, memory::heap_allocator> > pool(16, 17);
```
I get a compile error:

```
In file included from /Users/gabrielnuetzi/Desktop/ExecutionGraph/tests/src/main_MemoryPool.cpp:15:
In file included from /Users/gabrielnuetzi/Desktop/ExecutionGraph/buildExternal/install/memory/include/foonathan_memory/foonathan/memory/default_allocator.hpp:12:
In file included from /Users/gabrielnuetzi/Desktop/ExecutionGraph/buildExternal/install/memory/include/foonathan_memory/foonathan/memory/heap_allocator.hpp:15:
/Users/gabrielnuetzi/Desktop/ExecutionGraph/buildExternal/install/memory/include/foonathan_memory/foonathan/memory/allocator_traits.hpp:144:17: error: static_assert failed due to requirement 'std::is_default_constructible<fallback_allocator<lowlevel_allocator<detail::heap_allocator_impl>, lowlevel_allocator<detail::heap_allocator_impl> > >::value' "RawAllocator is empty but not default constructible .This means it is not a stateless allocator. If this is actually intended provide the appropriate is_stateful typedef in your class."
                static_assert(std::is_default_constructible<Allocator>::value,
                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Am I using it wrong?

**Comment by foonathan** [comment]
No, this shouldn't happen, I'll fix it.

But note that your code is wrong anyway: `memory::default_allocator` is not a composable RawAllocator (it does not provide a `try_allocate_node()` function because the matching `try_deallocate_node()` is impossible to implement). Why are you trying to do that?

**Comment by gabyx** [comment]
I am not yet very familiar with the concepts, thats probably the reason.
a I probably should use it the otherway around, or could you guide me towards the right direction :-)

```
using pool = memory::memory_pool_collection<memory::node_pool, memory::log2_buckets, allocator>;
using allocator = memory::fallback_allocator<pool, memory::heap_allocator>;

allocator al(pool{4000,1000000}, {});
```
?

**Comment by foonathan** [comment]
Yes, that's how you would use it: It's an allocator that tries to use a pool, then uses the heap allocator (if you fix the `allocator` typedef used in the pool line).

**Comment by gabyx** [comment]
thx!

**Comment by foonathan** [comment]
Does it work for you now? Besides the thread issue.

**Comment by gabyx** [comment]
Jep so far, yes :-), all tests I have done (without the strange threading issue) work :-). I did not yet try the
fallback allocator with a pool and heap_allocator, that will come usefull in a while then :-)
