### ISSUE TITLE
memory_pool and exception in thread

### ISSUE THREAD

**Issue by gabyx** [foonathan/memory#25]
I have a test code which allocates instances of `A` and hands the memory over into a `CefRefPtr`
a reference counted Wrapper which calls a virtual function `Release()`.
`A::Release()`obviously needs to destruct and deallocate over the memory pool, therefore I hand in a `std::function` (A::deleter). 
In my test setup (google test) everything works without any problems. However when I use this same loop in a thread (CEF IO Thread) the whole thing crashes with 
`EXC_BAD_ACCESS (code=EXC_I386_GPFLT)` at `allocate_node` at the third call. I cannot get to the source of the problem. Do you know if a thread can somehow limit the memory allocation. The strange thing is, I can replace the `memory_pool` with `heap_allocator` and everything works ?
Note that all my objects get constructed and deleted in the same function the thread is currently...
No resource ownership problems...

Do you have any idea what it could be...?

```cpp
// A ref counted class (CefRefPtr from Chromium Embedded Framework)
struct A : CefBaseRefCounted
{   
    template<typename D>
    A(int a, D&&d) : m_a{a}, deleter(d) {}
    ~A(){ std::cout << "dtor A :" << m_a[0] << std::endl;}
    int m_a[100];

    std::function<void(A*)> deleter; // Wrap here the deleter to delete over the pool
                                                           
    void AddRef() const override { m_refCount.AddRef(); }
    bool Release() const override 
    {
        if (m_refCount.Release())
        {
            deleter(const_cast<A*>(this));
            return true;
        }
        return false;                                               
    }
    bool HasOneRef() const override { return m_refCount.HasOneRef(); } 
    CefRefCount m_refCount;
};

MY_TEST(MemoryPool, Test1)
{
    using RawAllocator = memory_pool<>;
    using Ptr    = CefRefPtr<A>;
    using RawPtr = std::unique_ptr<A, allocator_deallocator<A, RawAllocator>>;

    RawAllocator pool(sizeof(A), sizeof(A)*10);
    std::vector<Ptr> vec;
    for(auto i = 0; i< 30000; ++i)
    {
        auto memory = pool.allocate_node(); // CRASH HERE at third call
        
         // raw_ptr deallocates memory in case of constructor exception
        RawPtr result(static_cast<A*>(memory), {pool});
        // call constructor (placement new)
        ::new(memory) A(i, [&pool](auto* p){ allocator_deleter<A, RawAllocator>{pool}(p); });
        // pass ownership to return value CefRefPtr which will use the internal A::deleter
        std::cout << "allocated " << i << std::endl;
        vec.emplace_back( Ptr(result.release()) );
    }
    std::shuffle(vec.begin(), vec.end(), std::mt19937{});
}
```

**Comment by foonathan** [comment]
Is the pool shared between threads? Because if so, you need to ensure that there are no race conditions, it isn't thread safe by default.

**Comment by gabyx** [comment]
no, I checked that `deleter(const_cast<A*>(this));` is always in the same thread, which is true.
so its deleted in the same thread I own the pool. (sounds right?)

**Comment by CapSel** [comment]
Have you tried address sanitizer and/or thread sanitizer? Could you post your code so we could try to reproduce it in our environment?

**Comment by gabyx** [comment]
Of course: 
The test code is here: 

Here with the CefRefPtr (which crashes when used in the CEF IO Thread)
but not in the manual test
https://github.com/gabyx/ExecutionGraph/blob/devGUI/gui/tests/src/main_MemoryPool.cpp

and the standalone manual test without CEF and anything, which works :-)
https://github.com/gabyx/ExecutionGraph/blob/devGUI/tests/src/main_MemoryPool.cpp

**Comment by gabyx** [comment]
I probably should try a thread sanitizer, but I am not really experienced with this kind of sanitizer...

**Comment by gabyx** [comment]
@CapSel : Would be glad to get a feed back from you, thanks for the effort

**Comment by gabyx** [comment]
![image](https://user-images.githubusercontent.com/647437/36759258-10331daa-1c17-11e8-9de1-2eaf0cbb746b.png)

**Comment by gabyx** [comment]
![bildschirmfoto 2018-02-27 um 23 50 28](https://user-images.githubusercontent.com/647437/36759849-100cb92e-1c19-11e8-9d9b-b3b362b6279d.png)

Ok it crashes at memcpy ?? @foonathan 
Could you enlighten what it is doing here?

**Comment by gabyx** [comment]
Ok, case closed, of course it was my fault: I build the library in debug mode. and saw, i made a type , and placement new placed a wrong size, not according to the pool setup. ups my bad!
thanks for your efforts!
