### ISSUE TITLE
nullptr as unique_ptr with Deleter 

### ISSUE THREAD

**Issue by gabyx** [foonathan/memory#28]
I have the following problem: I have a class `BinaryBuffer` which should have a default Ctor:
```cpp
using Deleter     = foonathan::memory::allocator_deleter<uint8_t[], RawAllocator>;
using BufferPtr  = std::unique_ptr<uint8_t[], Deleter>;

//! Constructor for an empty buffer!
    BinaryBuffer(std::shared_ptr<RawAllocator> allocator)
        : m_allocator(allocator)
        , m_data(nullptr, Deleter{foonathan::memory::make_allocator_reference(*allocator), 0})
    {}
```
It takes a RawAllocator which it keeps as reference (`m_allocator`). The data `m_data` is of type `BufferPtr`. My problem I am facing is, that I need a valid allocator smart pointer (not nullptr) such that I can setup the Deleter, even if the pointer is actually `nullptr`. Is there a way of having a default CTOR where I set the `m_data` member to nullptr, with an invalid deleter.
Is there such a wrapper like `make_allocator_pointer(allocator.get())` which wraps a pointer to the allocator internally which I can default to `nullptr`. Or can this be achieved similarly?

**Comment by foonathan** [comment]
Oh, so you want to have a default constructor for `allocator_deleter`?

**Comment by gabyx** [comment]
Basically yes :), such that I can set the `m_data` member to nullptr? Maybe its the wrong approach ?

**Comment by foonathan** [comment]
I'm not quite sure why you need it, the constructor you've shown takes an allocator anyway.

**Comment by gabyx** [comment]
Jeah, exactly, but I want to get rid of this shared_ptr -> a CTOR `BinaryBuffer()` which makes  `m_data = nullptr ` but its not that easy because of the deleter.

**Comment by foonathan** [comment]
I see. But is there a way to modify the deleter of a smart pointer?

**Comment by gabyx** [comment]
I am not quite sure, does that mean, once set, it will stay the same while copy/moving the smart pointer (moving in this case).
What I need is
```
std::unique_ptr<uint8_t[], Deleter> p(nullptr, Deleter{});
p = foo(); // move assigns to p,  p has now a valid deleter, copied from the return value
```
This is essentially a very related question on SO: https://stackoverflow.com/questions/35317344/unique-ptrs-assignment-operator-copies-a-deleter-stored-by-a-reference-is-it-a
Hm... might std::reference_wrapper help?

**Comment by gabyx** [comment]
If I see correctly: `allocator_storage<reference_storage<RawAllocator>, Mutex>` is the `allocator_reference`. If `get_allocator` in `allocator_storage` would return a pointer, then we could have a default ctor. The `allocator_storage::storage_policy::get_allocator` returns a reference, what about returning a pointer. If that pointer is `nullptr` 
```cpp
            void allocator_storage::deallocate_node(void* ptr, std::size_t size,std::size_t alignment) FOONATHAN_NOEXCEPT
{
    std::lock_guard<actual_mutex> lock(*this);
    auto*  alloc = get_allocator();
    if(alloc)
    {
                traits::deallocate_node(alloc, ptr, size, alignment);
    }
}
```

(of course if it is `nullptr`, all wrapped functions need to skip doing anything instead of a reference, we could have

**Comment by gabyx** [comment]
Some thoughts: The standart says: http://eel.is/c++draft/unique.ptr#single.dtor
> Effects: If get() == nullptr there are no effects. Otherwise get_­deleter()(get()).
So the deleter is not called if it is nullptr, so I suppose, we can store an empty deleter in it.

**Comment by gabyx** [comment]
sounds awesome, thanks!

**Comment by gabyx** [comment]
I have a related question:  I store my allocator in the `BinaryBuffer` as a smart pointer (to make sure it always exists)
Is there already a way of having an `allocator_storage` which stores a shared_ptr of an RawAllocator. Meaning, the deleter will store not a reference but a std::shared_ptr<RawAllocator> inside, removing the need to keeping the allocator next to my `m_data` member.

```cpp
//! Constructor for a meaningful buffer!
    BinaryBuffer(std::size_t bytes, std::shared_ptr<RawAllocator> allocator)
        : /*m_allocator(allocator) not needed anymore*/ 
        , m_data(foonathan::memory::allocate_unique<uint8_t[]>(allocator, bytes))
// ------------------------------------------------------------->*
//---------------------------------------------------------std::shared_ptr
        , m_bytes(bytes)
    {
    }
```

**Comment by foonathan** [comment]
Yes, you can write your own StoragePolicy (see the documentation for requirements). However, I won't add one using shared_ptr to the library, as I don't think it's an ideal solution. Usually you just have global variables or allocators in a top level function.

**Comment by gabyx** [comment]
ok thats true, also better, to be sure where its central location is, instead of wrapping it inside a deleter...
