### ISSUE TITLE
Prefix of compatibility options

### ISSUE THREAD

**Issue by twiggler** [foonathan/memory#29]
The [documentation](https://foonathan.net/doc/memory/md_doc_options.html) states that compatibility options can be overridden by setting `FOONATHAN_HAS_*` options. However, `FOONATHAN_HAS_THREAD_LOCAL`  can only be set by specifying `set(COMP_HAS_THREAD_LOCAL OFF CACHE BOOL "" FORCE)` in my makefile; thus, the prefix seems to be `COMP`, and not  `FOONATHAN`.

Incidentally, you might want to disable thread local support on gcc/mingw64; according to the comments in [this bug report](https://sourceforge.net/p/mingw-w64/bugs/527/), thread local support seems rather wonky. Personally, I got SEGFAULT' s on thread exit when using the  ` temporary_allocator`; by forcing `FOONATHAN_HAS_THREAD_LOCAL` to zero when compiling with gcc/MINGW64, everything is fine.

**Comment by foonathan** [comment]
I've corrected the docs and added a workaround in the comp-options branch. Please verify that your compiler is correctly detected (you should see a warning and no segfault).

**Comment by twiggler** [comment]
Verified:
- Warning emitted.
- No segfault.
👍 

Perhaps it would be better to incorporate the check for MINGW64 to the THREAD_LOCAL test in your compatibility library?

**Comment by foonathan** [comment]
No, the compabitility library only checks for the support of thread_local variables, which MinGW provides, it just lacks destructors.
