### ISSUE TITLE
Debug fence size causes misalignment.

### ISSUE THREAD

**Issue by twiggler** [foonathan/memory#30]
To enable SSE in the Eigen linear algebra library, data structures need to be 128bit-aligned. However, the FOONATHAN_MEMORY_DEBUG_FENCE default value is 8, which messes up alignment of Eigen structures. I tried to set the size using 

`set(FOONATHAN_MEMORY_DEBUG_FENCE 16 CACHE STRING "" FORCE)`
`set(FOONATHAN_MEMORY_DEBUG_FENCE_SIZE 16 CACHE STRING "" FORCE)`

to no avail. 
How can I configure the size of the debug fence?

**Comment by foonathan** [comment]
The debug options are set by the `CMAKE_BUILD_TYPE` used to compile the library, set it to Release when compiling it to disable the fence, for example.

But the fence itself shouldn't cause misalignment issues, which allocator are you using?

**Comment by twiggler** [comment]
An iteration_allocator.
You can see it happening [here](https://github.com/foonathan/memory/blob/b537a307f88356814dcfeb575f7e3d714493bd6f/include/foonathan/memory/detail/memory_stack.hpp#L96)

**Comment by foonathan** [comment]
Right, I didn't think that logic through, will fix.

**Comment by foonathan** [comment]
It is now fixed, every alignment is handled even with fence.

**Comment by twiggler** [comment]
Super 👍
