### ISSUE TITLE
Gradle cmake issue

### ISSUE THREAD

**Issue by daniellll3266** [foonathan/memory#35]
I have multiplatform library (Windows/Android/IOS/Linux) and I try to integrate and test your great library to all this projects. I have cmake project so integration to project files is pretty simple. Windows works very well after yesterday commit (thanks again).  It is possible compile your library with android NDK? I have problem with this cmake step:
`
# generate container_node_sizes.hpp
if(FOONATHAN_MEMORY_BUILD_TOOLS AND (NOT CMAKE_CROSS_COMPILING))
    add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/container_node_sizes_impl.hpp
            COMMAND foonathan_memory_node_size_debugger --code --alignof "FOONATHAN_ALIGNOF(T)" ${CMAKE_CURRENT_BINARY_DIR}/container_node_sizes_impl.hpp
            DEPENDS foonathan_memory_node_size_debugger
            VERBATIM)
else()
    message(WARNING "cannot generate container_node_sizes_impl.hpp, node size information will be unavailable")
    file(WRITE  ${CMAKE_CURRENT_BINARY_DIR}/container_node_sizes_impl.hpp "")
endif()
`
I obtained following error in gradle build:
foonathan_memory_node_size_debugger --code --alignof FOONATHAN_ALIGNOF(T) C:/.../cmake/fullRelease/arm64-v8a/SDK/Library/Headers/Library/Memory/3rdParty/src/container_node_sizes_impl.hpp"
  'foonathan_memory_node_size_debugger' is not recognized as an internal or external command,
  operable program or batch file.
  ninja: build stopped: subcommand failed.

I understand why it is a problem but exist any way to use it with android ndk and build application?

**Comment by daniellll3266** [comment]
Problem is that I compile with Clang for ARM  architecture on x86 architecture so I can not execute nodesize_dbg on my windows x86 pc but remotely on arm device. Its complicated. Exist any way to construct container_node_size_impl.hpp for arm?

**Comment by foonathan** [comment]
Ah, then you can't generate the node sizes at all (but CMake should have issued the error message in the else branch?). This is just a hack, and sadly it doesn't work for cross compiling.
