### ISSUE TITLE
Failed to configure tools using emscripten

### ISSUE THREAD

**Issue by CodingRays** [foonathan/memory#40]
When configuring for emscripten the cmake command returns the following error:
    
    cmake: /build/cmake-yjJ9_1/cmake-3.7.2/Source/cmOutputConverter.cxx:93: std::__cxx11::string cmOutputConverter::ConvertToRelativePath(const string&, const string&) const: Assertion `remote_path[0] != '\"'' failed.
    ERROR:root:Configure step failed with non-zero return code: -6.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/lrai/emsdk/node/8.9.1_64bit/bin/node" . -DCMAKE_TOOLCHAIN_FILE=/home/lrai/emsdk/emscripten/1.38.12/cmake/Modules/Platform/Emscripten.cmake at /mnt/c/Users/loren/Documents/Dev/Lib/foonathan/memory/build/emscripten
    
The configuration and building works when i set `FOONATHAN_MEMORY_BUILD_TOOLS` to `OFF`.
The entire build also works using msvc compilers so i assume my local copy isnt the problem.

As far as i can tell the tools are responsible for filling in the `container_node_sizes_impl.hpp` file, which my compiler tells me i do need.
Would it be difficult copy paste and adapt this file from one generated with native compilers?

**Comment by foonathan** [comment]
The error message does seem like a CMake issue though...

Basically, the tool creates a bunch of containers and remembers the size they wanted to allocate. This has to be done on the target machine. If the tool is disabled it should just create an empty `container_node_sizes_impl.hpp`, could you see whether that has been done?

You can of course manually create it, it's just a bunch of template specializations, but I'd recommend against it. If CMake doesn't want to do it, you can manually compile `node_size_debugger.cpp` (it's just a single file), but it has to be run on your target.

**Comment by CodingRays** [comment]
Yes it did create an empty file.
But i only realized it after my main project failed to find the templates that were supposed to be in that empty file.
It wasnt exactly hard to find the problem but maybe add a `#warn` to the `container_node_sizes_impl.hpp` file if the tools failed to make things easier to debug.

Im going to try to manually compile the file. I think i have an idea of what happened now.

**Comment by CodingRays** [comment]
The problem was that the tools program was unable to save the file from the virtual file system that emscripten created to the actually system fs. I dont know whether or not cmake knew that it had to invoke node instead of just running the file.

The fix was rather simple:
In the include section i had to add
```c++
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif
```
And at the beginning of the main function:
```c++
int main(int argc, char* argv[])
{
#ifdef __EMSCRIPTEN__
    EM_ASM(
        FS.mkdir('cwd');
        FS.mount(NODEFS, { root: '.' }, '/cwd');
    );
#endif
```

After this these small fixes the tool properly created the files. It does however limit the capabilities of the tool in the sense that it can only access the current working directory and that the file name passed as command line arguments had to be proceeded by cwd/.

**Comment by foonathan** [comment]
Okay, so I won't add it there myself.

Please let me know if you have any other issues.
