### ISSUE TITLE
map_node_size

### ISSUE THREAD

**Issue by ryanolson** [foonathan/memory#45]
I expected `memory::map_node_size` to take two template arguments, but rather it only takes one.

Expected:
```
memory::map_node_size<key_t, value_t>::value
```

Instead it only takes one template argument `T`.

What's the correct usage?

```
// do we use the value_type?
// c++17 gives us node_type
memory::map_node_size<std::map<key_t, value_t>::value_type>::value
```

**Comment by foonathan** [comment]
You use the `value_type` (i.e. pair of Key, Value). It should be equivalent to sizeof(node_type).
