### ISSUE TITLE
multi-threaded guidance

### ISSUE THREAD

**Issue by ryanolson** [foonathan/memory#47]
The library offers a couple ways to make the storage of an allocator thread-safe, either by directly or reference storage.  However, those storage policies don't get propagated if you extend the allocator into a tracker, as an std_allocator, etc.

If you want to create a stateful allocator whose state should be protected by a mutex in when used as a sub-allocator for higher-level allocators, what is the best practice?

Do you:
- create your own synchronization mutexes in the allocator
- create a new raw allocator that hold a thread-safe reference to the stateful (shared?) allocator and provide the link the allocator traits to the reference
- some other way?

**Comment by foonathan** [comment]
> However, those storage policies don't get propagated if you extend the allocator into a tracker, as an std_allocator, etc.

What do you mean by that?

> If you want to create a stateful allocator whose state should be protected by a mutex in when used as a sub-allocator for higher-level allocators, what is the best practice?

You can use `thread_safe_allocator<RawAllocator>` instead, which holds an allocator directly and synchronizing it with a mutex. https://github.com/foonathan/memory/blob/master/include/foonathan/memory/allocator_storage.hpp#L428
