### ISSUE TITLE
Default installation directory for library

### ISSUE THREAD

**Issue by hansfn** [foonathan/memory#48]
It seems PR #23 changed the default installation directory by changing [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) to `${CMAKE_BINARY_DIR}/install` - a directory "install" inside the current build directory.

If this is an intended change, the documentation should be updated - readme and https://foonathan.net/doc/memory/md_doc_installation.html 

I prefer that `CMAKE_INSTALL_PREFIX` is kept at the standard value.

**Comment by foonathan** [comment]
I am no longer sure about best practices for install, but I agree that changing it is probably a bad idea. Could you do a PR to update it?
