### ISSUE TITLE
cross compiling is broken

### ISSUE THREAD

**Issue by cvilas** [foonathan/memory#51]
Firstly, `CMAKE_CROSSCOMPILING` should be checked, not `CMAKE_CROSS_COMPILING`. Secondly, even with this fix, compile fails because of an empty `container_node_sizes_impl.hpp`.

**Comment by foonathan** [comment]
Should be fixed now, please let me know if there are further cross-compiling issues.

**Comment by cvilas** [comment]
Hi Jonathan. Thank you for the fix. 

Would you be able to briefly explain what the implications are of not building `node_size_debugger` when cross compiling? If I were to build on X86 host, could I use the `nodesize_dbg` binary built for X86 to generate `container_node_sizes_impl.hpp` and use that for all cross compilation targets? Asking this question because while this project now cross compiles, other projects that depend on it (eg: https://github.com/eProsima/Fast-RTPS) do not. Of course, this is _their_ problem not yours. But until they have fixed it, I would like to implement a workaround for myself!

Thanks

**Comment by foonathan** [comment]
The node size debugger is used to generate information about the size of e.g. a linked list node. This is not available in a portable way (until C++17 I believe), so the tool basically allocates and checks at runtime.

If you run on x86 you'll get the sizes for x86, which are probably wrong. You need to run the debugger on the correct target.

But the library itself is usable without it, you just don't get the size information.
