### ISSUE TITLE
Cmake version file name is wrong

### ISSUE THREAD

**Issue by moazzamak** [foonathan/memory#54]
When compiling with `make install` using cmake build directory prefix the output file generated to specify version info is named as `foonathan_memory-version.cmake` whereas cmake tries to look for `foonathan_memory-config-version.cmake`. This means that if you are trying to use `find_package(foonathan_memory 0.6.1)` with version number specified it will fail as it cannot find any version info. The file needs to be renamed to avoid this issue.

**Comment by foonathan** [comment]
If you do a PR, it'll be quicker. If so, could you also take a look at #48?

Help would be appreciated, I'm busy until after CppCon.

**Comment by moazzamak** [comment]
I can have a look at it during the weekend.
