### ISSUE TITLE
Memory pool collection thread safety

### ISSUE THREAD

**Issue by rahulcogent** [foonathan/memory#56]
First of all thanks for your work, this library is really useful.
I have a question regarding memory pool collection, unlike RawAllocator it is not thread safe. Is this intentional and by design? Does the responsibility to protect the pool lies with developer?

**Comment by foonathan** [comment]
That is correct, the responsibility to ensure thread safety lies with the user of the the thread pool. Sharing such local allocators between threads is usually not a good idea anyway, as this will lead to false sharing. The best solution is to create a pool per thread.
