### ISSUE TITLE
set_node_size not available when cross compiling

### ISSUE THREAD

**Issue by bdeeming** [foonathan/memory#57]
This is actually two issues I think (and perhaps simply need answers rather than fixes!).
When cross compiling Fast-RTPS which depends on `foonathan_memory` (which in my case was also built using cross-compilation immediately prior), I get the following errors:

```
In file included from /root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.h:32:0,
                 from /root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:22:
/root/workspace/install/include/foonathan_memory/foonathan/memory/container.hpp:376:31: error: expected template-name before '<' token
         : shared_ptr_node_size<T, std_allocator<T, RawAllocator, Mutex>>
                               ^
/root/workspace/install/include/foonathan_memory/foonathan/memory/container.hpp:376:31: error: expected '{' before '<' token
/root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:53:46: error: 'set_node_size' is not a member of 'memory'
 constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t>>::value;
                                              ^~~~~~~~~~~~~
/root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:53:46: note: suggested alternative: 'bad_node_size'
 constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t>>::value;
                                              ^~~~~~~~~~~~~
                                              bad_node_size
/root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:53:94: error: expected primary-expression before '>' token
 constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t>>::value;
                                                                                              ^~
/root/workspace/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:53:98: error: '::value' has not been declared
 constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t>>::value;
                                                                                                  ^~~~~
```

The first (`error: expected template-name before '<' token`) I resolved/avoided/hacked by adding an additional `#if !defined(FOONATHAN_MEMORY_NO_NODE_SIZE)` around `allocate_shared_node_size`  in `WriterProxy.cpp`.

The second(`'set_node_size' is not a member of 'memory'`) I'm not sure about. Is this expected to not be available in cross-compile mode? If it is then I'll raise a ticket against Fast-RTPS to avoid using it (since Fast-RTPS is designed for an embedded platform and is expected to be cross-compiled - in my opinion at least :smiley:).

Cheers!

**Comment by foonathan** [comment]
> The first (error: expected template-name before '<' token) I resolved/avoided/hacked by adding an additional #if !defined(FOONATHAN_MEMORY_NO_NODE_SIZE) around allocate_shared_node_size in WriterProxy.cpp.

This is an issue on my part, `allocate_shared_node_size` should not be available if `shared_ptr_node_size` isn't. I'll fix it later today.

> The second('set_node_size' is not a member of 'memory') I'm not sure about. Is this expected to not be available in cross-compile mode?

Yes, when cross-compiling, the `set_node_size` is the value for the *host* platform, not the *target* platform. As this is not what you want, I disable them in cross-compiling mode.

**Comment by bdeeming** [comment]
Thanks for the quick response! Suspected that might be the reason for it. Cheers.
