### ISSUE TITLE
Building release from tar-ball

### ISSUE THREAD

**Issue by hansfn** [foonathan/memory#63]
When you build from Git, the submodule cmake/comp is checked out. The files are missing from the tar-ball. Is there some easy way to fix this? I quickly tested but it seems the normal "git submodule update" command doesn't work since there is no .git folder in the tar-ball.

This is not a big problem. I can checkout the specific tag for the release and build as normal, but it should be documented if/how we can build from tar-balls. 

PS! Is there some specific reason why comp_base.cmake downloads "manually" a selected set of feature files, in stead of the parent project using an extra submodule for the master branch (which will fetch all feature sets). The reason I ask, is that downloading "manually" (when running CMake) failed with a curl error.

**Comment by foonathan** [comment]
I will get rid of compatibility soon anyway, as every check can be replaced using feature test macros.

**Comment by foonathan** [comment]
Every source file is now in the tar file, the submodule has been removed.
