### ISSUE TITLE
stateful no mutex ubsan alignment error

### ISSUE THREAD

**Issue by geoffviola** [foonathan/memory#64]
Ubsan detects some undefined behavior from misalignment in the "stateful no mutex" test in foonathan_memory_test.

I built the code with
```
cmake \
  -D CMAKE_BUILD_TYPE=Debug \
  -D CMAKE_CXX_FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined -Wall -Wcast-align -Wextra" \
  -D FOONATHAN_MEMORY_BUILD_TESTS=ON ..
```
The compiler is clang 9.0.1.

`./foonathan_memory_test` prints out
```
/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr_base.h:680:6: runtime error: constructor call on misaligned address 0x0000018e0094 for type '_Sp_cp_type' (aka '_Sp_counted_ptr_inplace<int, foonathan::memory::std_allocator<int, foonathan::memory::memory_pool<foonathan::memory::node_pool>, foonathan::memory::no_mutex>, (__gnu_cxx::_Lock_policy)2U>'), which requires 8 byte alignment
0x0000018e0094: note: pointer points here
  fd fd fd fd cd cd cd cd  cd cd cd cd cd cd cd cd  cd cd cd cd cd cd cd cd  cd cd cd cd cd cd cd cd
              ^ 
```

A backtrace showed the test in `test/smart_ptr.cpp`.
```
SECTION("stateful no mutex")
{
  memory_pool<> pool(allocate_shared_node_size<int, memory_pool<>, no_mutex>::value, 1024);
  auto          ptr = allocate_shared<int, no_mutex>(pool, 42);
  REQUIRE(*ptr == 42);
}
```

**Comment by foonathan** [comment]
Can't seem to reproduce it with clang 9.0.0 on ArchLinux. Nevertheless, I believe I have fixed the issue, could you try the branch feature/alignment?

**Comment by foonathan** [comment]
Nevermind, forgot to enable debug fences in my test; commit fixes them.

**Comment by geoffviola** [comment]
> Can't seem to reproduce it with clang 9.0.0 on ArchLinux. Nevertheless, I believe I have fixed the issue, could you try the branch feature/alignment?

Yes. That fixed it. Good job!
