### ISSUE TITLE
Shared pointer usage from multiple threads

### ISSUE THREAD

**Issue by rahulcogent** [foonathan/memory#66]
Hi,

Could you please take a look at the problem I am facing whenever you get time and help me if possible.

As I understand the memory pool is not protected by default and it should be protected if shared (ideally thread local). I am running into an issue where the library API needs to allocate memory and the API can be called from any number of threads so I can't guarantee thread local memory pool.
I get around the issue by protecting the allocation from pool using mutex. However, this still doesn't protect the deallocation. So code like this causes issue,
```
        {
            usleep(100); 
            allocMutex.lock();
            std::shared_ptr<TestSharedPointer> ptr1 = memory::allocate_shared<TestSharedPointer>(p, 10);  // Assume this allocate_shared is called from within API
            allocMutex.unlock();
            EXPECT_EQ(ptr1->getA(), 10);
        }
```
which is fixed, if I move the mutex out of scope thereby protecting deallocation.
  ```      
        allocMutex.lock();
       {
            usleep(100); 
            std::shared_ptr<TestSharedPointer> ptr1 = memory::allocate_shared<TestSharedPointer>(p, 10);
            EXPECT_EQ(ptr1->getA(), 10);
        }
        allocMutex.unlock();
```
However, such a solution is not possible since as an API developer I don't have control over the life span of allocated pointer.
Am I missing something here? Is this use case not supported?

**Comment by foonathan** [comment]
Instead of having a pool directly, create a `thread_safe_allocator`:

```cpp
auto safe_pool = memory::make_thread_safe_allocator(std::move(pool));
```

Then call `allocate_shared` passing the `safe_pool`:

```cpp
std::shared_ptr<TestSharedPointer> ptr1 = memory::allocate_shared<TestSharedPointer>(safe_pool, 10); 
```

`safe_pool` is basically a `pool` + mutex combination.
