### ISSUE TITLE
Full Documentation online

### ISSUE THREAD

**Issue by gabyx** [foonathan/memory#75]
Would be good to provide the full doxygen documentation online.
There is no class list, and navigating is hard.

e.g.: memory_pool_collection cannot be found... 

Thanks a lot!

**Comment by foonathan** [comment]
The documentation used to live in the same repository as my blog, when I moved it to a separate repo, I didn't really check much, sorry about that.

I've now fixed a couple of documentation issues that caused e.g. memory_pool_collection to be hidden. The new documentation has a list of all members here, they should now all be documented: https://foonathan.net/memory/namespacefoonathan_1_1memory.html (clicking on Index in the menu bar)

Let me know if there are any other issues.
