### ISSUE TITLE
assertion in memory_pool_collection

### ISSUE THREAD

**Issue by gabyx** [foonathan/memory#76]
```cpp
using namespace literals;
using Poolocator = memory_pool_collection<node_pool, identity_buckets>;
Poolocator alloc(1000_MiB, 4000_MiB);
```
Why am I not able to allocate this `memory_pool_collection`. 
Should'nt be the maximal node size 1Gb (meaning I can only allocat object of this maximal size) and the total managed memory block 4Gb
(I have enought ram, its not). It outputs the following on construction. What am I doing wrong?

```shell
[foonathan::memory] Assertion failure in function free_list_array (.../foonathan/memory/detail/free_list_array.hpp:41): Assertion "array_" failed.
```

**Comment by gabyx** [comment]
Ohh. I should have used `log2_buckets`.
identity_buckets would make buckets from 1bytes to 1 Gb, correct?
The assertion is somewhat strange...

**Comment by foonathan** [comment]
Yes, you're correct in your assessment. I've added a message to the assertion.
