### ISSUE TITLE
Can tracking be used with static_allocator?

### ISSUE THREAD

**Issue by grifcj** [foonathan/memory#79]
Is tracking supported for all raw allocators even simpler ones?
```
   auto tracked_static =
      memory::make_tracked_allocator(
         tracker{},
         memory::static_allocator(storage));
```

I found that I could not use the tracking with static_allocator or new_allocator due to them not having a `get_allocator` which is used in ctor and move ops of `tracked_allocator`.

Are these lines only meant for deeply_tracked_block_allocator feature? Basic tracking seemed to work without them.
```
set_tracker(get_allocator().get_allocator(), &get_tracker());
```

**Comment by foonathan** [comment]
Thanks, this was an oversight which I have now fixed.
