### ISSUE TITLE
catch.hpp unversioned download breaks builds

### ISSUE THREAD

**Issue by combinatorylogic** [foonathan/memory#83]
An URL for downloading Catch2 single include is pointing to master head. Currently, this header is broken, and builds depending on foonathan memory also break even when pinned to a specific version. URL currently in test/CMakeList.txt is  https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

I suggest replacing it with a specific hash reference, e.g., 
https://raw.githubusercontent.com/catchorg/Catch2/2e61d38c7c3078e600c331257b5bebfb81aaa685/single_include/catch2/catch.hpp - or, even better, just having a copy of that file locally. External unversioned downloads are not good for reproducible builds.

**Comment by foonathan** [comment]
I don't want to embed unrelated stuff in my git repo, but I'm now using a versioned link.
