### ISSUE TITLE
installation path for INC and RUNTIME set twice to two different values

### ISSUE THREAD

**Issue by asobhy-qnx** [foonathan/memory#86]
https://github.com/foonathan/memory/blob/a545595878e9ea434c08c303f885a68195445c1b/CMakeLists.txt#L24-L34

why are you setting FOONATHAN_MEMORY_INC_INSTALL_DIR and FOONATHAN_MEMORY_RUNTIME_INSTALL_DIR twice in the code block above? 

This is causing issues when cross compiling for QNX and trying to install the files in the location set by CMAKE_INSTALL_INCLUDEDIR and CMAKE_INSTALL_BINDIR

If you remove the last two lines from the code block above this will fix the problem.

**Comment by foonathan** [comment]
> why are you setting FOONATHAN_MEMORY_INC_INSTALL_DIR and FOONATHAN_MEMORY_RUNTIME_INSTALL_DIR twice in the code block above?

... I have no idea. Fixed.
