### ISSUE TITLE
Add support for QNX Neutrino

### ISSUE THREAD

**Issue by pablorcum** [foonathan/memory#90]
A new case was added for QNX recently at `src/CMakeLists.txt`. However, recent versions of CMake use the OS flag QNXNTO instead of QNX as shown [here](https://github.com/Kitware/CMake/blob/master/Modules/Platform/QNX.cmake).

Therefore, crosscompiling for newer versions of QNX is still not fully functional and may be overseen.

**Comment by foonathan** [comment]
I can't test that; can you do a PR?

**Comment by pablorcum** [comment]
Please change `elseif(QNX)` to `elseif(QNX OR QNXNTO)`.
