### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by roehling** [foonathan/memory#94]
I'm currently looking to get the library included with Debian, and I've seen you have quite a few fixes in the master branch and removed the compatibility dependency, which simplifies packaging quite a lot. Would it be possible to have a new 0.6-3 release any time soon?

Speaking of packaging, Debian has a strong preference for shared libraries, but the library doesn't seem to support this explicitly. Are there any technical pitfalls of which I should be aware?

**Comment by foonathan** [comment]
> Would it be possible to have a new 0.6-3 release any time soon?

Yes, I can prepare one this week or so, no problem.

> Speaking of packaging, Debian has a strong preference for shared libraries, but the library doesn't seem to support this explicitly. Are there any technical pitfalls of which I should be aware?

I have no idea.

**Comment by roehling** [comment]
Thanks! For the shared library, I'll try it and see what happens. ;-) The library requests raw memory via `mmap()`, which should generally play nice with the default allocators.

**Comment by foonathan** [comment]
It also uses new and malloc in some allocators.

**Comment by roehling** [comment]
From what I read now, `brk()` and `sbrk()` are problematic, everything else should be fine.

**Comment by roehling** [comment]
> Yes, I can prepare one this week or so, no problem.

Friendly nudge ;-)

**Comment by foonathan** [comment]
I'll release a new project tomorrow, once that's done I'll take care of this one. ;)

**Comment by foonathan** [comment]
Done.
